### ISSUE TITLE
Restarting training in CUDA mode

### ISSUE THREAD

**Issue by OMalenfantThuot** [atomistic-machine-learning/schnetpack#126]
Hi!
I am  still working with the src/scripts/schnetpack_qm9.py script.
When the training is stopped, I suppose I should be able to restart it from the checkpoint-xx.pth.tar files.
However, if the training is done with CUDA, an error occurs the second time:
```
INFO:root:training...
Traceback (most recent call last):
  File "/home/olimt/projects/rrg-cotemich-ac/olimt/programs/schnetpack/src/scripts/schnetpack_qm9.py", line 134, in <module>
    train(args, model, train_loader, val_loader, device, metrics=metrics)
  File "/home/olimt/miniconda3/lib/python3.7/site-packages/scripts/script_utils/training.py", line 54, in train
    trainer.train(device, n_epochs=args.n_epochs)
  File "/home/olimt/miniconda3/lib/python3.7/site-packages/schnetpack/train/trainer.py", line 245, in train
    raise e
  File "/home/olimt/miniconda3/lib/python3.7/site-packages/schnetpack/train/trainer.py", line 175, in train
    self.optimizer.step()
  File "/home/olimt/miniconda3/lib/python3.7/site-packages/torch/optim/adam.py", line 93, in step
    exp_avg.mul_(beta1).add_(1 - beta1, grad)
RuntimeError: expected backend CPU and dtype Float but got backend CUDA and dtype Float
```
There's probably a missing `.to('cuda')` somewhere.
I'll try to look into it more, but I wanted to let you know.
Thanks!

**Comment by OMalenfantThuot** [comment]
Ok so I found the problem and fixed it.
Currently, when the state_dict of the optimizer is loaded from the checkpoint file, it is not transfered to the GPU.
I have a fix available in the branch [fix_restart](https://github.com/OMalenfantThuot/schnetpack/tree/fix_restart) of my forked repo if you are interested. However, It requires adding `device` as an input for the declaration of a `spk.train.Trainer` instance. The scripts in `src/scripts/` are fine, but if this object is called from elsewhere in the code, this can cause problems.

This branch is only one commit ahead of your master, so the merging should be easy.
Thanks!

**Comment by ktschuett** [comment]
@Stefaanhess Is this issue solved with the new version?

**Comment by OMalenfantThuot** [comment]
Hi. The problem is still there in your master branch.
I could prepare a new branch with the fix and do a pull request if you wish, because the old one is now way behind.

**Comment by ktschuett** [comment]
@Stefaanhess is on it. There seem to be some necessary changes beyond the fix with the new version.

**Comment by Stefaanhess** [comment]
Hey @OMalenfantThuot ,

thanks for your solution. I used a modified version to fix the issue in #146 .
It should be working now.

**Comment by OMalenfantThuot** [comment]
Thanks!
