### ISSUE TITLE
TorchEnvironmentProvider

### ISSUE THREAD

**Issue by jduerholt** [atomistic-machine-learning/schnetpack#184]
Dear SchNetPack developers,

I tried to use the TorchEnvironmentProvider instead of the AseEnvironmentProvider for my system using a cutoff and PBCs for performance reasons, but I failed. I think there is a bug in the TorchEnvironmentProvider, but of course it could also be due to my incompetence :-) 

I provide for you a minimal working example showing the substantially different behavior of the ASE and Torch providers for the environment of atom with index 0 for my system of interest. In addition I computed the environment also by an easy Numpy based routine.

Perhaps, you can shed light to this rather strange behavior of the TorchEnvironmentProvider.

Best

Johannes

[mwe.tar.gz](https://github.com/atomistic-machine-learning/schnetpack/files/3854633/mwe.tar.gz)

**Comment by mgastegger** [comment]
You are right, there seems to be a problem with the TorchEnvironmentProvider. Those two should not give different results. We will have a look, let's see what light we can shed. Thanks for the example, that should help narrow it down.

Stress tensor, etc should work fine with the ASE provider, so you can use that instead until we fix the problem.

**Comment by mgastegger** [comment]
I found the problem and fixed it. Should now give the same results as ASE within random ordering. Generally, it seems that the ASE provider in its current incarnation is the better default choice, at least on CPU.

**Comment by jduerholt** [comment]
Thank you very much. I will test the performance for my use case on a RTX2080TI.

**Comment by mgastegger** [comment]
No problem, it's good you noticed the bug.

I would also be interested how both providers perform on GPU.

**Comment by jduerholt** [comment]
As soon as I find time, I will do the tests and post it here. Presumably, this will be next week since I am visiting Alexandre Tkatchenkos group for the rest of the week.
Best
Johannes

**Comment by OMalenfantThuot** [comment]
I was coming here for the same bug! Thanks a lot for the fix.

Would it be a problem to do more frequent releases for minor versions (0.3.1, 0.3.2, etc.)?
For this bugfix and in general.

It would help to maintain my own package and run automated tests.
For exemple, at the moment my interface is working with 0.3.0, but not with the master branch.

Thank you!

**Comment by OMalenfantThuot** [comment]
It seems the fix wasn't sufficient to totally bring the torch environment provider up to the ase level.

To reproduce the bug:
```
python spk_run.py from_json model/args.json
```
with the following `args.json`:
```
{
    "aggregation_mode": "sum",
    "batch_size": 10,
    "checkpoint_interval": 1,
    "contributions": null,
    "cuda": true,
    "cutoff": 7.0,
    "cutoff_function": "cosine",
    "datapath": "graph4.db",
    "dataset": "custom",
    "derivative": "forces",
    "environment_provider": "torch",
    "features": 128,
    "force": null,
    "interactions": 6,
    "keep_n_checkpoints": 3,
    "log_every_n_epochs": 1,
    "logger": "csv",
    "lr": 0.0001,
    "lr_decay": 0.8,
    "lr_min": 1e-06,
    "lr_patience": 25,
    "max_epochs": 10000,
    "max_steps": null,
    "mode": "train",
    "model": "schnet",
    "modelpath": "model/",
    "n_epochs": 10000,
    "negative_dr": true,
    "num_gaussians": 50,
    "output_module": "atomwise",
    "overwrite": false,
    "parallel": false,
    "property": "energy",
    "rho": {},
    "seed": null,
    "split": [
        100,
        50
    ],
    "split_path": null,
    "stress": null
}
```
The dataset is a custom dataset I generated, containing energy and forces.
You can get it [here](https://drive.google.com/file/d/1_9GURwprQXomd70SV2Ff_eQdPXIT3Yi4/view?usp=sharing)

With those parameters, the log looks like this:
```
Time,Learning rate,Train loss,Validation loss,MAE_energy,RMSE_energy,MAE_forces,RMSE_forces
4.030436038970947,0.0001,nan,nan,nan,nan,nan,nan
5.7937171459198,0.0001,nan,nan,nan,nan,nan,nan
7.532912969589233,0.0001,nan,nan,nan,nan,nan,nan
9.38976526260376,0.0001,nan,nan,nan,nan,nan,nan
```

If I train only on the energy, it works. If I change to ase environment provider, it also works.

I did some digging on the problem.
Using `torch.autograd.detect_anomaly` I got the following traceback:
```
Traceback (most recent call last):
  File "/home/olimt/projects/rrg-cotemich-ac/olimt/programs/schnetpack/src/scripts/spk_run.py", line 125, in <module>
    main(args)
  File "/home/olimt/projects/rrg-cotemich-ac/olimt/programs/schnetpack/src/scripts/spk_run.py", line 67, in main
    trainer.train(device, n_epochs=args.n_epochs)
  File "/lustre03/project/6004866/olimt/programs/schnetpack/src/schnetpack/train/trainer.py", line 276, in train
    raise e
  File "/lustre03/project/6004866/olimt/programs/schnetpack/src/schnetpack/train/trainer.py", line 203, in train
    loss.backward()
  File "/home/olimt/miniconda3/envs/ml/lib/python3.7/site-packages/torch/tensor.py", line 150, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/olimt/miniconda3/envs/ml/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function 'DivBackward0' returned nan values in its 0th output.
```

The first calculated loss (after the first training batch in the first epoch) is finite, but the `weight.grad` of the model modules are full of NaNs after the first `loss.backward()` call. Probably because of a division by 0.
Then, after the `optimizer.step()`the model is full of NaNs and every subsequent result is also NaN.

I'll use ASE from now on, but I tought you would like to know.

**Comment by mgastegger** [comment]
@OMalenfantThuot thanks a lot for the feedback, seems like there is  a problem with the masking of the distances somewhere. I will have a look. Regarding your interface, what is the problem with the current version of the master branch?

**Comment by OMalenfantThuot** [comment]
It's a minor thing (one of the inputs of `_convert_atoms()` changed name at some point).
But if I change it in my code, the CI tests will fail when I install schnetpack with pip.

**Comment by Dankomaister** [comment]
Could you give some details on which part of the code you change to get rid of the nan problem.
I get the same error trying to train my model on energies and forces using the TorchEnvironmentProvider.

**Comment by OMalenfantThuot** [comment]
I don't think the problem is fixed yet. I use the ase environment provider instead.

**Comment by mgastegger** [comment]
Yes, sorry, the issue still persists. As of now, please use the ASE environment provider. We are still trying to find the bug.

**Comment by jduerholt** [comment]
I think that there is one general problem for all current environment providers for production calculations. In every MD step (at least by using ASE) the environment is recalculated from scratch which means that the distances to all atoms have to be recalculated which should scale quadratic. Making use of neighborlists here should give massive speedups (at least for larger systems) and a better scaling behavior. I am working on a custom LAMMPS version which makes use of the LAMMPS neighborlist and calculates the environment on the C/C++ level and passes this information then to python, calculates energy and forces and passes this back. In principle it is already working but needs more testing and polishing. Would you be interested in such a thing?

**Comment by mgastegger** [comment]
Yes, this is still a big issue. There are plans to include more efficient neighbor schemes (for the MD package in particular), but to do so properly needs time. Hence, what you are working on does indeed sound very interesting to us. We'd be happy to test this in SchNetPack.

**Comment by mgastegger** [comment]
Finally found the bug in the torch provider. It now gives the same results during training as the ASE provider.
