### ISSUE TITLE
logging.py CSVHook small bug

### ISSUE THREAD

**Issue by stanos4** [atomistic-machine-learning/schnetpack#192]
Hi,

one more small bug - when restarting the trainer with CSVHook with existing log.csv file, it restarts "wrongly".
logging.py::CSVHook::__init__@line115 is:
self._offset = float(lines[-1].split(",")[0]) - time.time()

but should be:
self._offset = float(lines[-2].split(",")[0]) - time.time()

This bug will prevent restart of the training process.
(or some other place that writes "the last" newline to the file should be removed, but I didn't find that)

**Comment by Stefaanhess** [comment]
Hi @stanos4 ,
I am not sure what you mean. I just started a training session with a CSV hook, which interrupted after some epochs. When I started the same script again, it continued at the same point where I interrupted it without any errors. Did you run the scripts, or did you use your own code?

**Comment by stanos4** [comment]
I practically use the tutorial only, here are the steps (I just modified some cutoffs and batch sizes to see if I can increase my GPU utilization). But I'm running on Windows10 machine now, with the conda version of Schnetpack (conda install -c conda-forge schnetpack):

`import schnetpack as spk
from schnetpack.datasets import QM9
from torch.optim import Adam
import schnetpack.train as trn
import numpy as np
import matplotlib.pyplot as plt
from ase.units import kcal, mol
import torch
import time
import os

def mse_loss(batch, result):
    diff = batch[QM9.U0] - result[QM9.U0]
    err_sq = torch.mean(diff**2)
    return err_sq


qm9tut = os.getcwd()
environment_provider = spk.environment.TorchEnvironmentProvider(device='cuda', cutoff=8.0)
qm9data = QM9('qm9.db', download=False, load_only=[QM9.U0], remove_uncharacterized=True)
train, val, test = spk.train_test_split(data=qm9data, num_train=10000, num_val=500, split_file=os.path.join(qm9tut, "split.npz"))
train_loader = spk.AtomsLoader(val, batch_size=80, shuffle=True)
val_loader = spk.AtomsLoader(val, batch_size=80)
atomrefs = qm9data.get_atomref(QM9.U0)
means, stddevs = train_loader.get_statistics(QM9.U0, divide_by_atoms=True, single_atom_ref=atomrefs)
print(means, stddevs)
schnet = spk.representation.SchNet(n_atom_basis=30, n_filters=30, n_gaussians=20, n_interactions=5, cutoff=8., cutoff_network=spk.nn.cutoff.CosineCutoff)
output_U0 = spk.atomistic.Atomwise(n_in=30, atomref=atomrefs[QM9.U0], property=QM9.U0, mean=means[QM9.U0], stddev=stddevs[QM9.U0])

model = spk.AtomisticModel(representation=schnet, output_modules=output_U0)
optimizer = Adam(model.parameters(), lr=1e-2)

loss = trn.build_mse_loss([QM9.U0])
metrics = [spk.metrics.MeanAbsoluteError(QM9.U0)]
hooks = [trn.CSVHook(log_path=qm9tut, metrics=metrics), trn.ReduceLROnPlateauHook(optimizer, patience=5, factor=0.8, min_lr=1e-6, stop_after_min=True)]

trainer = trn.Trainer(model_path=qm9tut, model=model, hooks=hooks, loss_fn=loss, optimizer=optimizer, train_loader=train_loader, validation_loader=val_loader,checkpoint_interval=40, validation_interval=5)

device = "cuda"
#device = "cpu"
n_epochs = 300
trainer.train(device=device, n_epochs=n_epochs)`

then it's enough to rerun the last command and it will crash in my case.

**Comment by stanos4** [comment]
Also, yesterday I tested on another machine, linux this time (fedora 31 with cuda as well) and I can see that the csv log file is different. On windows, I get an empty line after each log record, on linux it's without the empty lines.

**Comment by Stefaanhess** [comment]
Oh, ok. Could you maybe also add the error message and the csv file?

**Comment by stanos4** [comment]
attached is the log and here is the error message:

    >>> trainer.train(device=device, n_epochs=n_epochs)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Users\XXX\AppData\Roaming\Python\Python37\site- 
    packages\schnetpack\train\trainer.py", line 163, in train
        h.on_train_begin(self)
      File "C:\Users\XXX\AppData\Roaming\Python\Python37\site- 
   packages\schnetpack\train\hooks\logging.py", line 115, in on_train_begin
        self._offset = float(lines[-1].split(",")[0]) - time.time()
    ValueError: could not convert string to float:


[log.txt](https://github.com/atomistic-machine-learning/schnetpack/files/3911375/log.txt)

**Comment by Stefaanhess** [comment]
Hi @stanos4 ,

Could you maybe try and run these lines on Windows and send me the resulting log files?

```
import os
with open("log_test_0.csv", "a+") as f:
  f.write("test test test" + os.linesep)
with open("log_test_0.csv", "a+") as f:
  f.write("test test test" + os.linesep)
```

and 

```
import os
with open("log_test_1.csv", "a+", newline="") as f:
  f.write("test test test" + os.linesep)
with open("log_test_1.csv", "a+", newline="") as f:
  f.write("test test test" + os.linesep)
```

I can not test on Windows, but maybe this already solves the problem.
Thanks!

**Comment by stanos4** [comment]
[log_test_0.txt](https://github.com/atomistic-machine-learning/schnetpack/files/3911584/log_test_0.txt)
[log_test_1.txt](https://github.com/atomistic-machine-learning/schnetpack/files/3911586/log_test_1.txt)

**Comment by Stefaanhess** [comment]
Thanks, #193 should fix the issue.

**Comment by stanos4** [comment]
sorry, but nope, still the same (I modified my source according to your patch).

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Users\ssimko\AppData\Local\Continuum\miniconda3\envs\schn\lib\site-packages\schnetpack\train\trainer.py", line 160, in train
        h.on_train_begin(self)
      File "C:\Users\ssimko\AppData\Local\Continuum\miniconda3\envs\schn\lib\site-packages\schnetpack\train\hooks\logging.py", line 115, in on_train_begin
        self._offset = float(lines[-1].split(",")[0]) - time.time()
    ValueError: could not convert string to float:

(there's a change - from line 163 to line 160, but I think it shouldn't matter)

**Comment by Stefaanhess** [comment]
Oh, ok. Could you please attach the log file again?

**Comment by Stefaanhess** [comment]
@stanos4 did you reinstall schnetpack, after you made the changes in the CSV logger? If not, you might need to activate your environment, go to the schnetpack folder and run:

```
>>> pip uninstall schnetpack
>>> pip install .
```

This reinstalls schnetpack, which should include your changes.

**Comment by stanos4** [comment]
I will give it a try tomorrow. However, I modified the "logging.py" file that was being used according to your patch (i.e. modifying single occurrence of file opening by passing the newline parameter), and upon restarting the python console it was still not working (modifying the same file by my "workaround" solves the error for me).

**Comment by stanos4** [comment]
Hi, sorry it took me so long. I just checked out the current git repo and installed with "pip install .", but the same problem persists:

    trainer.train(device=device, n_epochs=n_epochs)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Users\ssimko\AppData\Local\Programs\Python\Python37\lib\site-packages\schnetpack\train\trainer.py", line 160, in train
        h.on_train_begin(self)
      File "C:\Users\ssimko\AppData\Local\Programs\Python\Python37\lib\site-packages\schnetpack\train\hooks\logging.py", line 115, in on_train_begin
        self._offset = float(lines[-1].split(",")[0]) - time.time()
    ValueError: could not convert string to float:


There are still empty lines in the output log file (attached)
[log.txt](https://github.com/atomistic-machine-learning/schnetpack/files/3964146/log.txt)

**Comment by Stefaanhess** [comment]
fixed by #200
